var group__global =
[
    [ "BCCGAmokInfluence", "class_b_c_c_g_amok_influence.html", null ],
    [ "BCCGArmageddonInfluence", "class_b_c_c_g_armageddon_influence.html", null ],
    [ "BCCGAttackOrderInfluence", "class_b_c_c_g_attack_order_influence.html", null ],
    [ "BCCGWarCryInvisibleInfluence", "class_b_c_c_g_war_cry_invisible_influence.html", null ],
    [ "BCCGCryHavocInfluence", "class_b_c_c_g_cry_havoc_influence.html", null ],
    [ "BCCGCapDamageFromCardsSingleTurnInfluence", "class_b_c_c_g_cap_damage_from_cards_single_turn_influence.html", null ],
    [ "BCCGCauldronInfluence", "class_b_c_c_g_cauldron_influence.html", null ],
    [ "BCCGDamageMonstersWithRadiusInfluence", "class_b_c_c_g_damage_monsters_with_radius_influence.html", null ],
    [ "BCCGDamageNearestMonstersInConeInfluence", "class_b_c_c_g_damage_nearest_monsters_in_cone_influence.html", null ],
    [ "BCCGDarkPactInfluence", "class_b_c_c_g_dark_pact_influence.html", null ],
    [ "BCCGDemonicRevengeInfluence", "class_b_c_c_g_demonic_revenge_influence.html", null ],
    [ "BCCGDevourInfluence", "class_b_c_c_g_devour_influence.html", null ],
    [ "BCCGDummyInfluenceGlobal", "class_b_c_c_g_dummy_influence_global.html", null ],
    [ "BCCGGainScrewsOnKillTrapInfluence", "class_b_c_c_g_gain_screws_on_kill_trap_influence.html", null ],
    [ "BCCGIncreaseMonstersStrengthInfluence", "class_b_c_c_g_increase_monsters_strength_influence.html", null ],
    [ "BCCGChieftainInfluence", "class_b_c_c_g_chieftain_influence.html", null ],
    [ "BCCGJackTrapInfluence", "class_b_c_c_g_jack_trap_influence.html", null ],
    [ "BCCGLayingEggsInfluence", "class_b_c_c_g_laying_eggs_influence.html", null ],
    [ "BCCGMarkInfluence", "class_b_c_c_g_mark_influence.html", null ],
    [ "BCCGMarkTrapInfluence", "class_b_c_c_g_mark_trap_influence.html", null ],
    [ "BCCGPaintTrapInfluence", "class_b_c_c_g_paint_trap_influence.html", null ],
    [ "BCCGClassicTrapInfluence", "class_b_c_c_g_classic_trap_influence.html", null ],
    [ "BCCGModifyRandomMonsterStrengthInfluence", "class_b_c_c_g_modify_random_monster_strength_influence.html", null ],
    [ "BCCGMultiplayerCardUseInfluence", "class_b_c_c_g_multiplayer_card_use_influence.html", null ],
    [ "BCCGSinisterReverenceInfluence", "class_b_c_c_g_sinister_reverence_influence.html", null ],
    [ "BCCGMagicBarrierInfluence", "class_b_c_c_g_magic_barrier_influence.html", null ],
    [ "BCCGNonchalantInfluence", "class_b_c_c_g_nonchalant_influence.html", null ],
    [ "BCCGReduceMonsterStrengthInfluence", "class_b_c_c_g_reduce_monster_strength_influence.html", null ],
    [ "BCCGRoundRobinInfluence", "class_b_c_c_g_round_robin_influence.html", null ],
    [ "BCCGSpeedUpMonsterActionsInfluence", "class_b_c_c_g_speed_up_monster_actions_influence.html", null ],
    [ "BCCGStoneWallInfluence", "class_b_c_c_g_stone_wall_influence.html", null ],
    [ "BCCGSubsectorItemInfluence", "class_b_c_c_g_subsector_item_influence.html", null ],
    [ "BCCGSummonInfluence", "class_b_c_c_g_summon_influence.html", null ],
    [ "BCCGTrapRemovingBlockInfluence", "class_b_c_c_g_trap_removing_block_influence.html", null ]
];